USE [master]
GO

/****** Object:  Database [AirportSimDB]    Script Date: 30/01/2018 2:46:30 ******/
DROP DATABASE [AirportSimDB]
GO

/****** Object:  Database [AirportSimDB]    Script Date: 30/01/2018 2:46:30 ******/
CREATE DATABASE [AirportSimDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AirportSimDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\AirportSimDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AirportSimDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\AirportSimDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AirportSimDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AirportSimDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AirportSimDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AirportSimDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AirportSimDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AirportSimDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AirportSimDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AirportSimDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AirportSimDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AirportSimDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AirportSimDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AirportSimDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AirportSimDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AirportSimDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AirportSimDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AirportSimDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AirportSimDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AirportSimDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AirportSimDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AirportSimDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AirportSimDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AirportSimDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AirportSimDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AirportSimDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AirportSimDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AirportSimDB] SET  MULTI_USER 
GO

ALTER DATABASE [AirportSimDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AirportSimDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AirportSimDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AirportSimDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AirportSimDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AirportSimDB] SET QUERY_STORE = OFF
GO

USE [AirportSimDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AirportSimDB] SET  READ_WRITE 
GO


