//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAirportSim
{
	using System.Data.Entity;

	public partial class AirportEntities : DbContext
	{
		public AirportEntities()
			: base("AirportEntities")
		{
		}

		public virtual DbSet<AirportLog> AirportLogs { get; set; }
	}
}
